# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/colin/projects/adriencoin

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/colin/projects/adriencoin

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/colin/projects/adriencoin/CMakeFiles /home/colin/projects/adriencoin//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/colin/projects/adriencoin/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named discord-bot

# Build rule for target.
discord-bot: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 discord-bot
.PHONY : discord-bot

# fast build rule for target.
discord-bot/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/build
.PHONY : discord-bot/fast

src/cache.o: src/cache.cpp.o
.PHONY : src/cache.o

# target to build an object file
src/cache.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/src/cache.cpp.o
.PHONY : src/cache.cpp.o

src/cache.i: src/cache.cpp.i
.PHONY : src/cache.i

# target to preprocess a source file
src/cache.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/src/cache.cpp.i
.PHONY : src/cache.cpp.i

src/cache.s: src/cache.cpp.s
.PHONY : src/cache.s

# target to generate assembly for a file
src/cache.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/src/cache.cpp.s
.PHONY : src/cache.cpp.s

src/daily.o: src/daily.cpp.o
.PHONY : src/daily.o

# target to build an object file
src/daily.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/src/daily.cpp.o
.PHONY : src/daily.cpp.o

src/daily.i: src/daily.cpp.i
.PHONY : src/daily.i

# target to preprocess a source file
src/daily.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/src/daily.cpp.i
.PHONY : src/daily.cpp.i

src/daily.s: src/daily.cpp.s
.PHONY : src/daily.s

# target to generate assembly for a file
src/daily.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/src/daily.cpp.s
.PHONY : src/daily.cpp.s

src/graph/graph.o: src/graph/graph.cpp.o
.PHONY : src/graph/graph.o

# target to build an object file
src/graph/graph.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/src/graph/graph.cpp.o
.PHONY : src/graph/graph.cpp.o

src/graph/graph.i: src/graph/graph.cpp.i
.PHONY : src/graph/graph.i

# target to preprocess a source file
src/graph/graph.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/src/graph/graph.cpp.i
.PHONY : src/graph/graph.cpp.i

src/graph/graph.s: src/graph/graph.cpp.s
.PHONY : src/graph/graph.s

# target to generate assembly for a file
src/graph/graph.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/src/graph/graph.cpp.s
.PHONY : src/graph/graph.cpp.s

src/job.o: src/job.cpp.o
.PHONY : src/job.o

# target to build an object file
src/job.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/src/job.cpp.o
.PHONY : src/job.cpp.o

src/job.i: src/job.cpp.i
.PHONY : src/job.i

# target to preprocess a source file
src/job.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/src/job.cpp.i
.PHONY : src/job.cpp.i

src/job.s: src/job.cpp.s
.PHONY : src/job.s

# target to generate assembly for a file
src/job.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/src/job.cpp.s
.PHONY : src/job.cpp.s

src/leaderboard.o: src/leaderboard.cpp.o
.PHONY : src/leaderboard.o

# target to build an object file
src/leaderboard.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/src/leaderboard.cpp.o
.PHONY : src/leaderboard.cpp.o

src/leaderboard.i: src/leaderboard.cpp.i
.PHONY : src/leaderboard.i

# target to preprocess a source file
src/leaderboard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/src/leaderboard.cpp.i
.PHONY : src/leaderboard.cpp.i

src/leaderboard.s: src/leaderboard.cpp.s
.PHONY : src/leaderboard.s

# target to generate assembly for a file
src/leaderboard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/src/leaderboard.cpp.s
.PHONY : src/leaderboard.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/onEvent.o: src/onEvent.cpp.o
.PHONY : src/onEvent.o

# target to build an object file
src/onEvent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/src/onEvent.cpp.o
.PHONY : src/onEvent.cpp.o

src/onEvent.i: src/onEvent.cpp.i
.PHONY : src/onEvent.i

# target to preprocess a source file
src/onEvent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/src/onEvent.cpp.i
.PHONY : src/onEvent.cpp.i

src/onEvent.s: src/onEvent.cpp.s
.PHONY : src/onEvent.s

# target to generate assembly for a file
src/onEvent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/src/onEvent.cpp.s
.PHONY : src/onEvent.cpp.s

src/onReady.o: src/onReady.cpp.o
.PHONY : src/onReady.o

# target to build an object file
src/onReady.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/src/onReady.cpp.o
.PHONY : src/onReady.cpp.o

src/onReady.i: src/onReady.cpp.i
.PHONY : src/onReady.i

# target to preprocess a source file
src/onReady.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/src/onReady.cpp.i
.PHONY : src/onReady.cpp.i

src/onReady.s: src/onReady.cpp.s
.PHONY : src/onReady.s

# target to generate assembly for a file
src/onReady.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/src/onReady.cpp.s
.PHONY : src/onReady.cpp.s

src/player.o: src/player.cpp.o
.PHONY : src/player.o

# target to build an object file
src/player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/src/player.cpp.o
.PHONY : src/player.cpp.o

src/player.i: src/player.cpp.i
.PHONY : src/player.i

# target to preprocess a source file
src/player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/src/player.cpp.i
.PHONY : src/player.cpp.i

src/player.s: src/player.cpp.s
.PHONY : src/player.s

# target to generate assembly for a file
src/player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/src/player.cpp.s
.PHONY : src/player.cpp.s

src/product.o: src/product.cpp.o
.PHONY : src/product.o

# target to build an object file
src/product.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/src/product.cpp.o
.PHONY : src/product.cpp.o

src/product.i: src/product.cpp.i
.PHONY : src/product.i

# target to preprocess a source file
src/product.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/src/product.cpp.i
.PHONY : src/product.cpp.i

src/product.s: src/product.cpp.s
.PHONY : src/product.s

# target to generate assembly for a file
src/product.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/src/product.cpp.s
.PHONY : src/product.cpp.s

src/shop.o: src/shop.cpp.o
.PHONY : src/shop.o

# target to build an object file
src/shop.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/src/shop.cpp.o
.PHONY : src/shop.cpp.o

src/shop.i: src/shop.cpp.i
.PHONY : src/shop.i

# target to preprocess a source file
src/shop.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/src/shop.cpp.i
.PHONY : src/shop.cpp.i

src/shop.s: src/shop.cpp.s
.PHONY : src/shop.s

# target to generate assembly for a file
src/shop.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/src/shop.cpp.s
.PHONY : src/shop.cpp.s

src/stock.o: src/stock.cpp.o
.PHONY : src/stock.o

# target to build an object file
src/stock.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/src/stock.cpp.o
.PHONY : src/stock.cpp.o

src/stock.i: src/stock.cpp.i
.PHONY : src/stock.i

# target to preprocess a source file
src/stock.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/src/stock.cpp.i
.PHONY : src/stock.cpp.i

src/stock.s: src/stock.cpp.s
.PHONY : src/stock.s

# target to generate assembly for a file
src/stock.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/src/stock.cpp.s
.PHONY : src/stock.cpp.s

src/trade.o: src/trade.cpp.o
.PHONY : src/trade.o

# target to build an object file
src/trade.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/src/trade.cpp.o
.PHONY : src/trade.cpp.o

src/trade.i: src/trade.cpp.i
.PHONY : src/trade.i

# target to preprocess a source file
src/trade.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/src/trade.cpp.i
.PHONY : src/trade.cpp.i

src/trade.s: src/trade.cpp.s
.PHONY : src/trade.s

# target to generate assembly for a file
src/trade.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/discord-bot.dir/build.make CMakeFiles/discord-bot.dir/src/trade.cpp.s
.PHONY : src/trade.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... discord-bot"
	@echo "... src/cache.o"
	@echo "... src/cache.i"
	@echo "... src/cache.s"
	@echo "... src/daily.o"
	@echo "... src/daily.i"
	@echo "... src/daily.s"
	@echo "... src/graph/graph.o"
	@echo "... src/graph/graph.i"
	@echo "... src/graph/graph.s"
	@echo "... src/job.o"
	@echo "... src/job.i"
	@echo "... src/job.s"
	@echo "... src/leaderboard.o"
	@echo "... src/leaderboard.i"
	@echo "... src/leaderboard.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/onEvent.o"
	@echo "... src/onEvent.i"
	@echo "... src/onEvent.s"
	@echo "... src/onReady.o"
	@echo "... src/onReady.i"
	@echo "... src/onReady.s"
	@echo "... src/player.o"
	@echo "... src/player.i"
	@echo "... src/player.s"
	@echo "... src/product.o"
	@echo "... src/product.i"
	@echo "... src/product.s"
	@echo "... src/shop.o"
	@echo "... src/shop.i"
	@echo "... src/shop.s"
	@echo "... src/stock.o"
	@echo "... src/stock.i"
	@echo "... src/stock.s"
	@echo "... src/trade.o"
	@echo "... src/trade.i"
	@echo "... src/trade.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

